### ISSUE TITLE
feature removal for document-term matrix, feature removal for calculated topic model

### ISSUE THREAD

**Issue by EveGayer** [cophi-wue/cophi-toolbox#14]
Tools bereitstellen, die es ermöglichen zu überprüfen, ob ein feature_removal vor oder nach dem Topic modelling durchführen sollte.

**Comment by MHuberFaust** [comment]
Entfernen der Stopwörter/features aus einer erweiterten (ersten 200? Wörter) der topic-key matrix, damit die Topiclabel erstellt werden können.

**Comment by severinsimmler** [comment]
Fixed in branch `oop`.
