### ISSUE TITLE
delete unmaintained cophi-toolbox

### ISSUE THREAD

**Issue by severinsimmler** [cophi-wue/cophi-toolbox#23]
To avoid confusion, delete [this one](https://github.com/thvitt/cophi-toolbox).

Unless you want to keep it for nostalgic reasons, @thvitt.

**Comment by thvitt** [comment]
do we have the [ddw-output](https://github.com/thvitt/cophi-toolbox/tree/master/ddw-output) subtree somewhere else?

**Comment by severinsimmler** [comment]
Oh nice, I didn't know we had this. I just copy-pasted it into a [new branch](https://github.com/cophi-wue/cophi-toolbox/tree/ddw), but someone should review this code.

However, that seems to me to be a very special feature, and we would have two new dependencies (networkx, nltk). Should the third-party libraries of this module only be installed with a special flag (e.g. `--ddw`)? I would not import the module in `__init__.py` that you still can use the library without it. Or should you _always_ get _all_ dependencies installed?
