### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by severinsimmler** [cophi-wue/cophi-toolbox#25]
There are now tests for the whole library ([tests](https://github.com/cophi-wue/cophi-toolbox/tree/testing/tests)), but Jenkins' last [build fails](http://dev.digital-humanities.de/ci/blue/organizations/jenkins/cophi_toolbox/detail/cophi_toolbox/50/pipeline):

```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```
BTW, I renamed the package from `cophi_toolbox` to `cophi`, because according to [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names):
> Python packages should also have short, all-lowercase names, although the **use of underscores is discouraged**.

Maybe that's the cause of the error?

**Comment by thvitt** [comment]
No, problem was that you moved the setup.cfg away in 58fe1c58eeb132c0dbb4f7884a50fb2dc6f124cf which contains the configuration that causes the xUnit-formatted test report to be written.

**Comment by severinsimmler** [comment]
Thank you! 👍
